# Generated by Build Tool (see Engine/Tools/Build for details)

set(SOURCE
    "./Zeroth.InputAxes.SaitekX52.yaml"
    "./ZerothSettings.yaml"
    )

source_group("Settings" FILES ${SOURCE})

set(SOURCE_FILES
    ${SOURCE}
    )

