---
video_mode:
    width: 1440
    height: 900
    bits_per_pixel: 32
    fullscreen: false
archives:
  - path: Zeroth.data
task_pool:
    thread_count: 6
asset_cache:
    concurrent: true
logging:
    levels: [ Info, Error, Warning ]
scene: Scenes/Client.scene
include: [ DefaultInputAxes.yaml ]
