# Generated by Build Tool (see Engine/Tools/Build for details)

set(SOURCE_MATERIALS
    "Materials/GalaxyImposter.Fragment.glsl"
    "Materials/GalaxyImposter.material.yaml"
    "Materials/GalaxyImposter.png"
    "Materials/GalaxyImposter.shader.yaml"
    "Materials/GalaxyImposter.texture2.yaml"
    "Materials/GalaxyImposter.Vertex.glsl"
    )

source_group("Assets\\Materials" FILES ${SOURCE_MATERIALS})

set(SOURCE_SCENES
    "Scenes/Client.scene.yaml"
    "Scenes/Intergalactic.scene.yaml"
    )

source_group("Assets\\Scenes" FILES ${SOURCE_SCENES})

set(SOURCE_TEST
    "Test/MonkeyHead.blend"
    "Test/MonkeyHead.mesh"
    )

source_group("Assets\\Test" FILES ${SOURCE_TEST})

set(SOURCE_FILES
    ${SOURCE_MATERIALS}
    ${SOURCE_SCENES}
    ${SOURCE_TEST}
    )

