# Generated by Build Tool (see Engine/Tools/Build for details)

set(SOURCE_SCENES
    "Scenes/Client.scene.yaml"
    "Scenes/Intergalactic.scene.yaml"
    )

source_group("Assets\\Scenes" FILES ${SOURCE_SCENES})

set(SOURCE_FILES
    ${SOURCE_SCENES}
    )

