# Generated by Build Tool (see Engine/Tools/Build for details)

set(SOURCE_ENTITIES
    "Entities/LocalPlayerBase.entity.yaml"
    )

source_group("Assets\\Entities" FILES ${SOURCE_ENTITIES})

set(SOURCE_SCENES
    "Scenes/Client.scene.yaml"
    )

source_group("Assets\\Scenes" FILES ${SOURCE_SCENES})

set(SOURCE_FILES
    ${SOURCE_ENTITIES}
    ${SOURCE_SCENES}
    )

